<a href="https://colab.research.google.com/github/mhkim0908/undergraduate-codes/blob/main/Lecture_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lecture 2
written by **MINHYEOK KIM** (2016008077, Dept. of Applied physics)

> Contents :  Basic of Python

*   Modules & Packages
*   Built-in Functions
*   Flow control
*   Data Types





## 2-1. Modules and Packages
**A module** is a file containing Python definitions and statements. The file name is the module name with the *suffix .py* appended. Within a module, the module’s name (as a string) is available as the value of the global variable $ __name__$. 

**Packages** are a way of structuring Python’s module namespace by using “dotted module names”. For example, the module name A.B designates a submodule named B in a package named A. Just like the use of modules saves the authors of different modules from having to worry about each other’s global variable names, the use of dotted module names saves the authors of multi-module packages like **NumPy** or **Pillow** from having to worry about each other’s module names.

To sum it up, Packages are collections of modules, and the modules are collections of functions. 

For instance, we'll look at the **math** module.

To use this module, we have to get module by using an **import** statement.

    import math
If the package (or module) name is followed by **as**, then the name following **as** is bound directly to the imported package. This is effectively importing the package or module in the same way, with the only difference of it being available as user-defiened name.



In [ ]:
import math as mh
mh.cos(mh.pi)

-1.0

The Math module provides access to the mathematical functions defined by the C standard. You can check which function does it have by using built-in function ***dir()***

In [ ]:
import math
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

With **From** statement, you can import specific functions in module. (Note that this doesn't introduce the module name. i.e., in example, ***math*** is not defined.)

In [ ]:
from math import cos,pi
cos(pi)

-1.0

If you want to call whole modules by from statement, you can use * symbol

In [ ]:
from math import *
cos(pi)

-1.0

For example, we can converting polar coordinates to Cartesian coordinates with math module

In [ ]:
from math import *

#input r,theta from users
r,theta = input('r value? : '),input('theta value? (degree):' )
#pretreatment -  set data type 
r,theta = float(r),float(theta)
radtheta = radians(theta)
#converting 
x = r*cos(radtheta)
y = r*sin(radtheta)
f'The value you entered (r,theta) is {r},{theta} and converted cartesian coordinate (x,y) = {x},{y}'

r value? : 50
theta value? (degree):30


'The value you entered (r,theta) is 50.0,30.0 and converted cartesian coordinate (x,y) = 43.30127018922194,24.999999999999996'

In Google Colababoratoy (our environment), there are many pre-built packages but not all. To install (or update) package in Google Colab., we can use **!pip install** ***(package_name)*** statement. 
For example,

    !pip install chart_studio
and Coalb takes care of the rest.

In [ ]:
!pip install chart_studio

     |████████████████████████████████| 71kB 3.5MB/s 


## 2-2. Built-in functions
Python gives some tools names of built-in functions. Such as print, float, int, input, etc is including.

These functions are defined in the standard module **builtins**. So you can also check these functions using ***dir(builtins)***

In [ ]:
import builtins
dir(builtins)

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EnvironmentError',
 'Exception',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'RuntimeError',
 'RuntimeWarning',
 'StopAsyncIteration',
 'StopIter

## 2-3 Flow control
In python, users can control the work-flow with few statements - ***IF, WHILE, FOR*** are perhaps the most well-known flow control statement. Let's see one by one.  

### 2-3-1 ***IF*** statement
I think ***If*** statement is probably the most popular statement. ***if*** statement is used for decision making. For instance:

In [ ]:
#Case 1.
data = input('Please enter a number that is multiples of 3: ')

#exception handling with try,except statement - we'll see later.
try:
    data = int(data)
except ValueError:
    print("PLEASE ENTER A NUMBER ONLY, NOT CHARACTER")
else:
    #IF Statement!
    if data%3 == 0:
        print('Your input {data} is multiples of 3. Thank you.'.format(data=data))
    elif data%77 == 0:
        print('I especially love multiples of 77 - the number you enetered')
    else:
        print('Your number {} is not multiples of 3. Try again.'.format(data))

Please enter a number that is multiples of 3: 7777
I especially love multiples of 77 - the number you enetered


In [ ]:
#Case 2.
data = input('Please enter a number that is multiples of 3: ')

#exception handling with try,except statement - we'll see later.
try:
    data = int(data)
except ValueError:
    print("PLEASE ENTER A NUMBER ONLY, NOT CHARACTER")
else:
    #IF Statement!
    if data%3 == 0:
        print('Your input {data} is multiples of 3. Thank you.'.format(data=data))
    elif data%77 == 0:
        print('I especially love multiples of 77 - the number you enetered')
    else:
        print('Your number {} is not multiples of 3. Try again.'.format(data))

Please enter a number that is multiples of 3: 995
Your number 995 is not multiples of 3. Try again.


In [ ]:
#Case 3.
data = input('Please enter a number that is multiples of 3: ')

#exception handling with try,except statement - we'll see later.
try:
    data = int(data)
except ValueError:
    print("PLEASE ENTER A NUMBER ONLY, NOT CHARACTER")
else:
    #IF Statement!
    if data%3 == 0:
        print('Your input {data} is multiples of 3. Thank you.'.format(data=data))
    elif data%77 == 0:
        print('I e7specially love multiples of 77 - the number you enetered')
    else:
        print('Your number {} is not multiples of 3. Try again.'.format(data))

Please enter a number that is multiples of 3: 7777
I especially love multiples of 77 - the number you enetered


In [ ]:
#Case 0. exception case
data = input('Please enter a number that is multiples of 3: ')

#exception handling with try,except statement - we'll see later.
try:
    data = int(data)
except ValueError:
    print("PLEASE ENTER A NUMBER ONLY, NOT CHARACTER")
else:
    #IF Statement!
    if data%3 == 0:
        print('Your input {data} is multiples of 3. Thank you.'.format(data=data))
    elif data%77 == 0:
        print('I especially love multiples of 77 - the number you enetered')
    else:
        print('Your number {} is not multiples of 3. Try again.'.format(data))

Please enter a number that is multiples of 3: 싫은데
PLEASE ENTER A NUMBER ONLY, NOT CHARACTER


In example, We checked how if statement control the workflow. ***If*** condition is **TRUE**, next indentation action is triggered. But the condition is **False**, the next statement is not executed. Instead, ***elif*** statement or ***else*** statement is work in order. ***elif*** means **Else if**. With ***elif*** statement, we can add another conditions. There can be zero or more elif parts, and the ***else*** part is optional. An if … elif … elif … sequence is a substitute for the switch or case statements found in other languages.

As the condition of if statement, any operator that returns True or False can be used.

Meanwhile, I used ***try***, ***except*** statement - that is used to handle exception cases. In the example **#case 0**, I have to filter non-number input to not raise an error (because ***int()*** can use only in numbers).  If the user entered a non-number value, the program return our warning message rather than a raw error message. Else, we go to the normal process.

###2-3-2 ***While*** statement
The ***while*** statement is used for repeated execution as long as an expression is true. You can think this as a loop.



In [ ]:
i = 1 
while i<10:
    print(i)
    if i == 3:
        break
    i += 1

1
2
3


This repeatedly tests the expression and, if it is true, executes the first suite - ***print(i)***; if the expression is false (which may be the first time it is tested) the suite of the else clause, if present, is executed and the loop terminates.

A ***break*** statement executed in the first suite terminates the loop without executing the else clause’s suite. A ***continue*** statement executed in the first suite skips the rest of the suite and goes back to testing the expression.

In [ ]:
i = 1 
while i<10:
    print(i)
    if i == 3:
        continue
    i += 1

As the result of above example, the number 3 will keep print out. i.e.,

    3
    3
    3
    3
    3
    3
    ...
I don't recommend you to run the above code... but if you are still curious what happened, try it :)


Another example for while statement - Find the Fibonacci sequence up to n.

In [ ]:
#Find the Fibonacci sequence up to n.
n_value = input("I'll find you the Fibonacci sequence up to n. Enter integer n value here: ")
try:
    n = int(n_value)
except ValueError:
    print("PLEASE ENTER A NUMBER ONLY, NOT CHARACTER")
else:
    a,b = 1,1
    while a<n:
        print(a, end='   ')
        a,b = b, a+b

I'll find you the Fibonacci sequence up to n. Enter integer n value here: 10000
1   1   2   3   5   8   13   21   34   55   89   144   233   377   610   987   1597   2584   4181   6765   

### 2-3-3 ***For*** statement 

Python’s ***for*** statement iterates over the items of any sequence (a list or a string), in the order that they appear in the sequence.

In [ ]:
physicists = ['Einstein','Faraday','Bohr','Schrodinger']
for i in physicists:
    print(i,len(i))

Einstein 8
Faraday 7
Bohr 4
Schrodinger 11


By using ***range()*** fucntion, you can iterate over a sequence of numbers. It generates arithmetic progressions.

In [ ]:
for i in range(5):
    print(i)

#you can give start point and end point.

for i in range(10,15):
    print(i)

0
1
2
3
4
10
11
12
13
14


We say such an object is iterable, that is, suitable as a target ***for*** functions and constructs that expect something from which they can obtain successive items until the supply is exhausted. We have seen that the ***for*** statement is such a construct, while an example of a function that takes an iterable is ***sum()***:

In [ ]:
print(sum(range(4)))   # 0+1+2+3 = 6
print(sum(range(5,10)))   # 5+6+7+8+9 = 35

print(list(range(20,30))) # make list with numbers in range 20~29

6
35
[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]


## 2-4. Data Types
We'll see rest of data types.

*  Numbers
*  String
*  **List**
*  **Tuple**
*  **Dictionary**

### 2-4-1 List
List is the most basic type of container which can be written as a list of comma-separated values (items) between square brackets. Lists might contain items of different types, but usually the items all have the same type.


In [ ]:
fibo=[1,1,2,3,5,8,13,21]
print(fibo)

[1, 1, 2, 3, 5, 8, 13, 21]


lists can be indexed and sliced:

In [ ]:
print(fibo[0]) # indexing returns the item - start from 0
print(fibo[-1]) # minus index returns the item in reverse order
print(fibo[-3:])  # slicing returns a new list

1
21
[8, 13, 21]


Lists also support operations like concatenation:

In [ ]:
print(fibo + [6,9,12])

[1, 1, 2, 3, 5, 8, 13, 21, 6, 9, 12]


Unlike strings, which are immutable, lists are a **mutable** type, i.e., it is possible to change their content:



In [ ]:
wrong_fibo=[1,1,2,3,5,8,13,22] #wrong value here
wrong_fibo[-1] = 21 #replace 22 to 21
print(wrong_fibo)

[1, 1, 2, 3, 5, 8, 13, 21]


The built-in function ***len()*** can applies to lists:



In [ ]:
numbers=[1,2,3,4,5]
print(len(numbers))

5


You can also add new items at the end of the list, by using the ***list.append()*** method. The item will be add to the end of the list. Equivalent to a  [len(a):] = [x].

Assignment to slices is also possible, and this can even change the size of the list or clear it entirely.


Also, It is possible to nest lists (create lists containing other lists), for example:






In [ ]:
numbers = [1,2,3,4,5,6,7,8,9,10]
print(numbers)
numbers.append(999)
print(numbers)
numbers.append([77,88,99,111]) #containg list
print(numbers)
print(numbers[-1]) #print appeded list
print(numbers[-1][0]) #print appended list's first element
numbers[2:5] = [11,21,31,41,51]
print(numbers)
numbers[2:5] = []
print(numbers)
numbers[:] = []
print(numbers)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 999]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 999, [77, 88, 99, 111]]
[77, 88, 99, 111]
77
[1, 2, 11, 21, 31, 41, 51, 6, 7, 8, 9, 10, 999, [77, 88, 99, 111]]
[1, 2, 41, 51, 6, 7, 8, 9, 10, 999, [77, 88, 99, 111]]
[]


The list data type has some more methods. Here are all of the methods of list objects:

*    ***list.extend(iterable)***
>    Extend the list by appending all the items from the iterable. Equivalent to a [len(a):] = iterable.

*    ***list.insert(i, x)***
>    Insert an item at a given position. The first argument is the index of the element before which to insert, so ***a.insert(0, x)*** inserts at the front of the list, and ***a.insert(len(a), x)*** is equivalent to ***a.append(x)***.

*    ***list.remove(x)***
>    Remove the first item from the list whose value is equal to x. It raises a ValueError if there is no such item.

*    ***list.pop([i])***
>    Remove the item at the given position in the list, and return it. If no index is specified, ***a.pop()*** removes and returns the last item in the list. (The square brackets around the i in the method signature denote that the parameter is *optional*, not that you should type square brackets at that position.)

*    ***list.clear()***
>    Remove all items from the list. Equivalent to del a[:].

*    ***list.index(x[, start[, end]])***
>    Return zero-based index in the list of the first item whose value is equal to x. Raises a ValueError if there is no such item. The optional arguments start and end are interpreted as in the slice notation and are used to limit the search to a particular subsequence of the list. The returned index is computed relative to the beginning of the full sequence rather than the start argument.

*    ***list.count(x)*** 
>    Return the number of times x appears in the list.

*    ***list.sort(*, key=None, reverse=False)*** 
>    Sort the items of the list in place (the arguments can be used for sort customization, see sorted() for their explanation).

*    ***list.reverse()***
>    Reverse the elements of the list in place.

*    ***list.copy()***
>    Return a shallow copy of the list. Equivalent to a[:].

Check next example

In [ ]:
subjects = ['Physics','Physics','Computational Physics','Quantum Mechanics','Electrodynamics','Condensed Matter Physics', 'Quantum Computing', 'Physics' ]
print(subjects.count('Physics'))
print(subjects.count('Classical Dynamics'))
print(subjects.index('Physics'))
print(subjects.index('Physics',3,8))
subjects.reverse()
print(subjects)
subjects.sort()
print(subjects)
print(subjects.pop())
print(subjects.pop(1))

3
0
0
7
['Physics', 'Quantum Computing', 'Condensed Matter Physics', 'Electrodynamics', 'Quantum Mechanics', 'Computational Physics', 'Physics', 'Physics']
['Computational Physics', 'Condensed Matter Physics', 'Electrodynamics', 'Physics', 'Physics', 'Physics', 'Quantum Computing', 'Quantum Mechanics']
Quantum Mechanics
Condensed Matter Physics


If list have elements as numbers, we can apply arithmetic built-in-functions.

In [ ]:
r = [1.0, 1.5, 2.2, 4.0]
total = sum(r)
print(total)

mean = sum(r)/len(r)
print(mean)

print(max(r),min(r))

8.7
2.175
4.0 1.0


To apply other arithmetic functions on list elements, we have to use ***map(func, *iterables)***.

This make an iterator that computes the function using arguments from
each of the iterables. Stops when the shortest iterable is exhausted.

In [ ]:
from math import log,sqrt,cos,radians

r = [1.0, 4.0, 9.0, 16.0]

print(list(map(log,r)))

print(list(map(sqrt,r)))

print(list(map(cos,r)))

print(list(map(radians,r)))

[0.0, 1.3862943611198906, 2.1972245773362196, 2.772588722239781]
[1.0, 2.0, 3.0, 4.0]
[0.5403023058681398, -0.6536436208636119, -0.9111302618846769, -0.9576594803233847]
[0.017453292519943295, 0.06981317007977318, 0.15707963267948966, 0.2792526803190927]


### 2-4-2 Array
Actually, there is no 'array' data type in python. An array is a variable that can store multiple values in the C language. Since many C language users demand 'array', Python provide 'array' built-in module. Or you can use array with third-party module such as **Numpy**. 

**Array** module defines an object type which can compactly represent an array of basic values: characters, integers, floating point numbers. Arrays are sequence types and behave very much like lists, except that **the type of objects stored in them is constrained**. The type is specified at object creation time by using a type code, which is a single character. The following type codes are defined:

Type code | C Type | Python Type
--- | --- | ---
'b' | Signed char		 | int
'B' | unsigned char		 | int
'u' | wchar_t	 | Unicode character
'h' | signed short		 | int
'H' | unsigned short		 | int
'i' |signed int		 | int
'I' (caprital i) |unsigned int		 | int
'l' (small L)|signed long		 | int
'L' |unsigned long		 | int
'q' |signed long long		 | int
'Q' |unsigned long long		 | int
'f' |float		 | float
'd' |double		 | float

----
Array objects support the ordinary sequence operations of indexing, slicing, concatenation, and multiplication. When using slice assignment, the assigned value must be an array object with the same type code; in all other cases, TypeError is raised. 

You can declare array like this.
``` python
    from array import *
    arrayName = array(type, [Values])
```

Python has a set of built-in methods that you can use on lists/arrays.

Method | Description
--- | --- 
array.append() |Adds an element at the end of the list
array.clear() | Removes all the elements from the list
array.copy() | Returns a copy of the list
array.count() | Returns the number of elements with the specified value
array.extend() |Add the elements of a list (or any iterable), to the end of the current list
array.index() |Returns the index of the first element with the specified value
array.insert() |Adds an element at the specified position 
array.pop()|Removes the element at the specified position
array.remove() |Removes the first item with the specified value
array.reverse() |Reverses the order of the list	 
array.sort() |Sorts the list		 	 



---


Let's check example below

In [ ]:
from array import *

myarray = array('i',[1,2,3,3,4,5])
print(myarray)
print(myarray.typecode) #check myarray's type code
print(myarray[0])
print(myarray.count(3))
myarray.insert(1,50) # insert number '50' 2nd position in array
print(myarray)
myarray.remove(3) # you have to specify name of member, not index number
print(myarray)
print(myarray.index(50)) # This is a function to search index values through values.
myarray[1] = 30 # You can update element's value through index number
print(myarray)

array('i', [1, 2, 3, 3, 4, 5])
i
1
2
array('i', [1, 50, 2, 3, 3, 4, 5])
array('i', [1, 50, 2, 3, 4, 5])
1
array('i', [1, 30, 2, 3, 4, 5])


Here is Array's several significant advantages :
1. Arrays can be two-dimensional, like matrices in algebra. Lists are always just one-dimensional.
2. Arrays behave roughly like **vectors** or **matrices**: you can do arithmetic with them, such as adding them together. 
3. Arrays work faster than lists.

In [ ]:
from numpy import zeros,ones,empty
a= zeros(4,float)
print(a)
b = zeros([6,7],float) # Two-dimensional float array 
print(b)
c = ones([6,7],float)
print(c)
d = empty([6,7],float)
print(d)  

[0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


You could also make 2-Dimensional array with **Numpy** module. With Numpy's N-dimensional array function - An ndarray. ndarray is a multidimensional container of items of the same type and size. You can construct array like : 
```python
ndarray(shape[, dtype, buffer, offset, …])
```

In [ ]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
y = np.array([[7, 0, 0], [0, 7, 0],[0,0,7]], np.int32)
z= np.array([1,2,3,4],np.int32)

print('type',type(x))
print('size',x.size)
print('shape',x.shape)
print('dtype',x.dtype)
print('itemszie',x.itemsize)

print('x',x)
print('x_min',x.min())
print('x_max',x.max())
print('x transpose',x.T) #transpose
print('y',y)
print(np.dot(x,y)) #dot product
print('z',z)
print('z,sum()',z.sum())

print('z+1',z+1)
print(2*x)


#example in ppt
a=np.array([[1,3],[2,4]],np.int32)
b=np.array([[4,-2],[-3,1]],np.int32)
c=np.array([[1,2],[2,1]],np.int32)

print(np.dot(a,b)+2*c)

type <class 'numpy.ndarray'>
size 6
shape (2, 3)
dtype int32
itemszie 4
x [[1 2 3]
 [4 5 6]]
x_min 1
x_max 6
x transpose [[1 4]
 [2 5]
 [3 6]]
y [[7 0 0]
 [0 7 0]
 [0 0 7]]
[[ 7 14 21]
 [28 35 42]]
z [1 2 3 4]
z,sum() 10
z+1 [2 3 4 5]
[[ 2  4  6]
 [ 8 10 12]]
[[-3  5]
 [ 0  2]]


For more information, [Check this document](https://numpy.org/doc/stable/reference/arrays.ndarray.html)

### 2-4-3 Tuple
Tuples are immutable sequences, typically used to store collections of heterogeneous data (such as the 2-tuples produced by the enumerate() built-in). Tuples are also used for cases where an immutable sequence of homogeneous data is needed (such as allowing storage in a set or dict instance).

Tuples may be constructed in a number of ways:

*    Using a pair of parentheses to denote the empty tuple: ()

*    Using a trailing comma for a singleton tuple: a, or (a,)

*    Separating items with commas: a, b, c or (a, b, c)

*    Using the tuple() built-in: tuple() or tuple(iterable)

The constructor builds a tuple whose items are the same and in the same order as iterable’s items. iterable may be either a sequence, a container that supports iteration, or an iterator object. If iterable is already a tuple, it is returned unchanged. For example, tuple('abc') returns ('a', 'b', 'c') and tuple( [1, 2, 3] ) returns (1, 2, 3). If no argument is given, the constructor creates a new empty tuple, ().

Note that it is actually the comma which makes a tuple, not the parentheses. The parentheses are optional, except in the empty tuple case, or when they are needed to avoid syntactic ambiguity. For example, f(a, b, c) is a function call with three arguments, while f((a, b, c)) is a function call with a 3-tuple as the sole argument.

Tuples implement all of the common sequence operations.


In [ ]:
t = 12345, 54321, 'hello!'
print(t[0])

print(t)

# Tuples may be nested:
u = t, (1, 2, 3, 4, 5)
print(u)


#they can contain mutable objects:
v = ([1, 2, 3], [3, 2, 1])
print(v)

empty = ()
singleton = 'hello',    # <-- note trailing comma
print(len(empty))
print(len(singleton))
print(singleton)

12345
(12345, 54321, 'hello!')
((12345, 54321, 'hello!'), (1, 2, 3, 4, 5))
([1, 2, 3], [3, 2, 1])
0
1
('hello',)


### 2-4-4 Dictionary

Another useful data type built into Python is the dictionary. 

It is best to think of a dictionary as a set of key: value pairs, with the requirement that the keys are unique (within one dictionary). A pair of braces creates an empty dictionary: {}. Placing a comma-separated list of key:value pairs within the braces adds initial key:value pairs to the dictionary; this is also the way dictionaries are written on output.

The main operations on a dictionary are storing a value with some key and extracting the value given the key. It is also possible to delete a key:value pair with del. If you store using a key that is already in use, the old value associated with that key is forgotten. It is an error to extract a value using a non-existent key.

Performing list(d) on a dictionary returns a list of all the keys used in the dictionary, in insertion order (if you want it sorted, just use sorted(d) instead). To check whether a single key is in the dictionary, use the in keyword.

Here is a small example using a dictionary:

In [ ]:
tel = {'jack': 4098, 'sape': 4139}
tel['guido'] = 4127
print(tel)
print(tel['jack'])
del tel['sape']
tel['irv'] = 4127
print(tel)
print(list(tel))
print(sorted(tel))
print('guido' in tel)
print('jack' not in tel)

tell =  dict([('sape', 4139), ('guido', 4127), ('jack', 4098)])
print(tell)

k = {x: x**2 for x in (2, 4, 6)}
print(k)

{'jack': 4098, 'sape': 4139, 'guido': 4127}
4098
{'jack': 4098, 'guido': 4127, 'irv': 4127}
['jack', 'guido', 'irv']
['guido', 'irv', 'jack']
True
False
{'sape': 4139, 'guido': 4127, 'jack': 4098}
{2: 4, 4: 16, 6: 36}


##3. Examples
In this section, I'll calculate Mean, Mean-square, Geometric mean, Harmonic mean for values.txt file with using ***For*** statement.

The Definition of Generalized mean is as below.

$$ \bar{x}(m) = (\frac{1}{n} \cdot \sum_{i=1}^{n}x_i^{m})^{\frac{1}{m}}$$ 
where $m$ is a non-zero real number and $x_i$ are positive real numbers.
$$ m\rightarrow \infty : \quad maximum \ of \ x_i \\ m=2 : \quad quadratic \ mean \\ m=1 : \quad arithmetic \ mean \\ m \rightarrow 0: \quad geometric \ mean \\ m = -1: \quad harmonic \ mean \\ m \rightarrow -\infty: \quad minimum \ of \ x_i $$

In [ ]:
#Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#Load Value file
import numpy as np
values = np.loadtxt('/content/drive/MyDrive/values.txt',float)
print(values.shape, type(values))

(1000,) <class 'numpy.ndarray'>


In [ ]:
n = len(values)
quadx_i, aritx_i, harmx_i, geox_i= 0, 0, 0, 0 #initial condition

for i in range(0,len(values)):
    quadx_i += values[i]**2
    aritx_i += values[i]**1
    harmx_i += values[i]**-1
    geox_i += values[i]**0.00000000001          # we can't describe lim x->0

quadratic = ((1/n)*(quadx_i))**(1/2)
arithmetic = ((1/n)*(aritx_i))**(1/1)
harmonic = ((1/n)*(harmx_i))**(1/-1)
geometric = ((1/n)*(geox_i))**(np.inf) # 1/0 = infinity

print('quadratic:',quadratic, 'arithmetic:',arithmetic, 'harmonic:',harmonic, 'geometric:', geometric)

quadratic: 0.581706194631797 arithmetic: 0.5028284649993353 harmonic: 0.11795531622472907 geometric: 0.0


By the way, is the geometric mean of values.txt is 0.0? Let's check with built-in module functions.

In [ ]:
#Comparison results with built-in module functions
from scipy.stats.mstats import gmean,hmean
#quadratic 
print('quadratic: ',np.sqrt(np.mean(values**2)))
#arithmetic
print('arithmetic: ',np.mean(values))
#geometric
print('geometric: ' , gmean(values))
#harmonic 
print('harmonic:', hmean(values))

quadratic:  0.5817061946317968
arithmetic:  0.5028284649993354
geometric:  0.3679958355128421
harmonic: 0.11795531622472909


Scipy module says the geometric mean is 0.36799..., not 0.0. Why does our Generalized power mean method is not working for geometric mean in python? I think It's beacuse we couldn't describe limitation very well.
Let's try another method.

Geometric mean is defined as 

$$ {\displaystyle \left(\prod _{i=1}^{n}x_{i}\right)^{\frac {1}{n}}={\sqrt[{n}]{x_{1}x_{2}\cdots x_{n}}}} $$

Let's try this method.

In [ ]:
n = len(values)
geox_i = 1 
for i in range(0,len(values)):
    geox_i *= values[i]
geometric = geox_i**(1/n)
print(geometric)
#Python can't calculate in this way either...

0.0


The **Generalized power mean** could be generalized further to the **Generalized f-mean** or quasi-arithmetic mean. (It is also called Kolmogorov mean) 
$$ \bar{x} = f^{-1} (\frac{1}{n} \cdot \sum_{i=1}^{n} f(x_i))$$
We require $f$ to be injective in order for the inverse function ${f^{-1}}$ to exist.

$$ f(x) = x : \quad arithmetic \ mean \\ f(x) = \frac{1}{x} : \quad harmonic \ mean \\ f(x) = x^m : \quad \ power \ mean \\ f(x) = ln(x) : \quad geometic \ mean$$

In [ ]:
n = len(values)

arisum, harsum, powsum, geosum = 0 , 0, 0, 0

for i in range(0,len(values)):
    arisum += values[i]
    harsum += (1/values[i])
    geosum += np.log(values[i])

f_arithmetic = ((1/n)*arisum)
f_geometric = e**((1/n)*geosum)
f_harsum = 1/((1/n) * harsum)

print('arithmetic: ',f_arithmetic, 'f_harmonic: ',f_harsum, 'f_geometirc: ',f_geometric) #we can now calculate geometric mean with python!

arithmetic:  0.5028284649993353 f_harmonic:  0.11795531622472907 f_geometirc:  0.36799583551284204


## References
1. https://docs.python.org/3/tutorial/controlflow.html
2. https://docs.python.org/3/tutorial/datastructures.html
3. https://docs.python.org/3/tutorial/modules.html
4. https://docs.python.org/3/tutorial/inputoutput.html
5. https://numpy.org/doc/stable/reference/arrays.ndarray.html